// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: codex_credential.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CodexCredentialLoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodexCredentialLoadRequest) Reset() {
	*x = CodexCredentialLoadRequest{}
	mi := &file_codex_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodexCredentialLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodexCredentialLoadRequest) ProtoMessage() {}

func (x *CodexCredentialLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodexCredentialLoadRequest.ProtoReflect.Descriptor instead.
func (*CodexCredentialLoadRequest) Descriptor() ([]byte, []int) {
	return file_codex_credential_proto_rawDescGZIP(), []int{0}
}

type CodexCredentialLoadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque credential bytes. This field is sensitive and must never be logged.
	Credential []byte `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	// Kubernetes resource version used as the compare-and-swap generation.
	Generation    string `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodexCredentialLoadResponse) Reset() {
	*x = CodexCredentialLoadResponse{}
	mi := &file_codex_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodexCredentialLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodexCredentialLoadResponse) ProtoMessage() {}

func (x *CodexCredentialLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codex_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodexCredentialLoadResponse.ProtoReflect.Descriptor instead.
func (*CodexCredentialLoadResponse) Descriptor() ([]byte, []int) {
	return file_codex_credential_proto_rawDescGZIP(), []int{1}
}

func (x *CodexCredentialLoadResponse) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *CodexCredentialLoadResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

type CodexCredentialReplaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The generation returned by Load. Empty only creates an absent credential.
	ExpectedGeneration string `protobuf:"bytes,1,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	// Opaque credential bytes. This field is sensitive and must never be logged.
	Credential    []byte `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodexCredentialReplaceRequest) Reset() {
	*x = CodexCredentialReplaceRequest{}
	mi := &file_codex_credential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodexCredentialReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodexCredentialReplaceRequest) ProtoMessage() {}

func (x *CodexCredentialReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_credential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodexCredentialReplaceRequest.ProtoReflect.Descriptor instead.
func (*CodexCredentialReplaceRequest) Descriptor() ([]byte, []int) {
	return file_codex_credential_proto_rawDescGZIP(), []int{2}
}

func (x *CodexCredentialReplaceRequest) GetExpectedGeneration() string {
	if x != nil {
		return x.ExpectedGeneration
	}
	return ""
}

func (x *CodexCredentialReplaceRequest) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

type CodexCredentialReplaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodexCredentialReplaceResponse) Reset() {
	*x = CodexCredentialReplaceResponse{}
	mi := &file_codex_credential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodexCredentialReplaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodexCredentialReplaceResponse) ProtoMessage() {}

func (x *CodexCredentialReplaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codex_credential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodexCredentialReplaceResponse.ProtoReflect.Descriptor instead.
func (*CodexCredentialReplaceResponse) Descriptor() ([]byte, []int) {
	return file_codex_credential_proto_rawDescGZIP(), []int{3}
}

func (x *CodexCredentialReplaceResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

var File_codex_credential_proto protoreflect.FileDescriptor

const file_codex_credential_proto_rawDesc = "" +
	"\n" +
	"\x16codex_credential.proto\x12\x1bagentgateway.dev.credential\"\x1c\n" +
	"\x1aCodexCredentialLoadRequest\"]\n" +
	"\x1bCodexCredentialLoadResponse\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\fR\n" +
	"credential\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\tR\n" +
	"generation\"p\n" +
	"\x1dCodexCredentialReplaceRequest\x12/\n" +
	"\x13expected_generation\x18\x01 \x01(\tR\x12expectedGeneration\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\fR\n" +
	"credential\"@\n" +
	"\x1eCodexCredentialReplaceResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation2\x98\x02\n" +
	"\x16CodexCredentialService\x12y\n" +
	"\x04Load\x127.agentgateway.dev.credential.CodexCredentialLoadRequest\x1a8.agentgateway.dev.credential.CodexCredentialLoadResponse\x12\x82\x01\n" +
	"\aReplace\x12:.agentgateway.dev.credential.CodexCredentialReplaceRequest\x1a;.agentgateway.dev.credential.CodexCredentialReplaceResponseB1Z/github.com/agentgateway/agentgateway/go/api;apib\x06proto3"

var (
	file_codex_credential_proto_rawDescOnce sync.Once
	file_codex_credential_proto_rawDescData []byte
)

func file_codex_credential_proto_rawDescGZIP() []byte {
	file_codex_credential_proto_rawDescOnce.Do(func() {
		file_codex_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codex_credential_proto_rawDesc), len(file_codex_credential_proto_rawDesc)))
	})
	return file_codex_credential_proto_rawDescData
}

var file_codex_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_codex_credential_proto_goTypes = []any{
	(*CodexCredentialLoadRequest)(nil),     // 0: agentgateway.dev.credential.CodexCredentialLoadRequest
	(*CodexCredentialLoadResponse)(nil),    // 1: agentgateway.dev.credential.CodexCredentialLoadResponse
	(*CodexCredentialReplaceRequest)(nil),  // 2: agentgateway.dev.credential.CodexCredentialReplaceRequest
	(*CodexCredentialReplaceResponse)(nil), // 3: agentgateway.dev.credential.CodexCredentialReplaceResponse
}
var file_codex_credential_proto_depIdxs = []int32{
	0, // 0: agentgateway.dev.credential.CodexCredentialService.Load:input_type -> agentgateway.dev.credential.CodexCredentialLoadRequest
	2, // 1: agentgateway.dev.credential.CodexCredentialService.Replace:input_type -> agentgateway.dev.credential.CodexCredentialReplaceRequest
	1, // 2: agentgateway.dev.credential.CodexCredentialService.Load:output_type -> agentgateway.dev.credential.CodexCredentialLoadResponse
	3, // 3: agentgateway.dev.credential.CodexCredentialService.Replace:output_type -> agentgateway.dev.credential.CodexCredentialReplaceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_codex_credential_proto_init() }
func file_codex_credential_proto_init() {
	if File_codex_credential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codex_credential_proto_rawDesc), len(file_codex_credential_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codex_credential_proto_goTypes,
		DependencyIndexes: file_codex_credential_proto_depIdxs,
		MessageInfos:      file_codex_credential_proto_msgTypes,
	}.Build()
	File_codex_credential_proto = out.File
	file_codex_credential_proto_goTypes = nil
	file_codex_credential_proto_depIdxs = nil
}
