// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package api

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for CodexCredentialLoadRequest
func (this *CodexCredentialLoadRequest) MarshalJSON() ([]byte, error) {
	str, err := CodexCredentialMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CodexCredentialLoadRequest
func (this *CodexCredentialLoadRequest) UnmarshalJSON(b []byte) error {
	return CodexCredentialUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CodexCredentialLoadResponse
func (this *CodexCredentialLoadResponse) MarshalJSON() ([]byte, error) {
	str, err := CodexCredentialMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CodexCredentialLoadResponse
func (this *CodexCredentialLoadResponse) UnmarshalJSON(b []byte) error {
	return CodexCredentialUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CodexCredentialReplaceRequest
func (this *CodexCredentialReplaceRequest) MarshalJSON() ([]byte, error) {
	str, err := CodexCredentialMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CodexCredentialReplaceRequest
func (this *CodexCredentialReplaceRequest) UnmarshalJSON(b []byte) error {
	return CodexCredentialUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for CodexCredentialReplaceResponse
func (this *CodexCredentialReplaceResponse) MarshalJSON() ([]byte, error) {
	str, err := CodexCredentialMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CodexCredentialReplaceResponse
func (this *CodexCredentialReplaceResponse) UnmarshalJSON(b []byte) error {
	return CodexCredentialUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CodexCredentialMarshaler   = &jsonpb.Marshaler{}
	CodexCredentialUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
