// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: codex_credential.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodexCredentialService_Load_FullMethodName    = "/agentgateway.dev.credential.CodexCredentialService/Load"
	CodexCredentialService_Replace_FullMethodName = "/agentgateway.dev.credential.CodexCredentialService/Replace"
)

// CodexCredentialServiceClient is the client API for CodexCredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CodexCredentialService persists one shared OAuth credential for the caller's
// Kubernetes namespace. The authenticated server derives that namespace; clients
// cannot select another namespace.
type CodexCredentialServiceClient interface {
	Load(ctx context.Context, in *CodexCredentialLoadRequest, opts ...grpc.CallOption) (*CodexCredentialLoadResponse, error)
	Replace(ctx context.Context, in *CodexCredentialReplaceRequest, opts ...grpc.CallOption) (*CodexCredentialReplaceResponse, error)
}

type codexCredentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodexCredentialServiceClient(cc grpc.ClientConnInterface) CodexCredentialServiceClient {
	return &codexCredentialServiceClient{cc}
}

func (c *codexCredentialServiceClient) Load(ctx context.Context, in *CodexCredentialLoadRequest, opts ...grpc.CallOption) (*CodexCredentialLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodexCredentialLoadResponse)
	err := c.cc.Invoke(ctx, CodexCredentialService_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codexCredentialServiceClient) Replace(ctx context.Context, in *CodexCredentialReplaceRequest, opts ...grpc.CallOption) (*CodexCredentialReplaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodexCredentialReplaceResponse)
	err := c.cc.Invoke(ctx, CodexCredentialService_Replace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodexCredentialServiceServer is the server API for CodexCredentialService service.
// All implementations must embed UnimplementedCodexCredentialServiceServer
// for forward compatibility.
//
// CodexCredentialService persists one shared OAuth credential for the caller's
// Kubernetes namespace. The authenticated server derives that namespace; clients
// cannot select another namespace.
type CodexCredentialServiceServer interface {
	Load(context.Context, *CodexCredentialLoadRequest) (*CodexCredentialLoadResponse, error)
	Replace(context.Context, *CodexCredentialReplaceRequest) (*CodexCredentialReplaceResponse, error)
	mustEmbedUnimplementedCodexCredentialServiceServer()
}

// UnimplementedCodexCredentialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodexCredentialServiceServer struct{}

func (UnimplementedCodexCredentialServiceServer) Load(context.Context, *CodexCredentialLoadRequest) (*CodexCredentialLoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedCodexCredentialServiceServer) Replace(context.Context, *CodexCredentialReplaceRequest) (*CodexCredentialReplaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replace not implemented")
}
func (UnimplementedCodexCredentialServiceServer) mustEmbedUnimplementedCodexCredentialServiceServer() {
}
func (UnimplementedCodexCredentialServiceServer) testEmbeddedByValue() {}

// UnsafeCodexCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodexCredentialServiceServer will
// result in compilation errors.
type UnsafeCodexCredentialServiceServer interface {
	mustEmbedUnimplementedCodexCredentialServiceServer()
}

func RegisterCodexCredentialServiceServer(s grpc.ServiceRegistrar, srv CodexCredentialServiceServer) {
	// If the following call panics, it indicates UnimplementedCodexCredentialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodexCredentialService_ServiceDesc, srv)
}

func _CodexCredentialService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodexCredentialLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodexCredentialServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodexCredentialService_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodexCredentialServiceServer).Load(ctx, req.(*CodexCredentialLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodexCredentialService_Replace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodexCredentialReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodexCredentialServiceServer).Replace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodexCredentialService_Replace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodexCredentialServiceServer).Replace(ctx, req.(*CodexCredentialReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodexCredentialService_ServiceDesc is the grpc.ServiceDesc for CodexCredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodexCredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentgateway.dev.credential.CodexCredentialService",
	HandlerType: (*CodexCredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _CodexCredentialService_Load_Handler,
		},
		{
			MethodName: "Replace",
			Handler:    _CodexCredentialService_Replace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "codex_credential.proto",
}
